FROM amazoncorretto:23-alpine  as scan-server

# to source epicsENV
RUN apk add --no-cache bash

ADD scan-server-fnal/target/fnal-scan-server*.jar /scan-server/fnal-scan-server.jar

EXPOSE 4810

CMD ["java", "-jar", "/scan-server/fnal-scan-server.jar", "-help"]

