name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'
  workflow_dispatch:

env:
  PHOEBUS_RELEASE: v5.0.2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Maven settings for GitHub Packages
      shell: bash
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
            <server>
              <id>github-fermi-auth</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.FERMIAUTH }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>github-packages</id>
              <repositories>
                <repository>
                  <id>github</id>
                  <url>https://maven.pkg.github.com/fermi-ad/phoebus-fnal</url>
                </repository>
                <repository>
                  <id>github-fermi-auth</id>
                  <url>https://maven.pkg.github.com/fermi-ad/java-keycloak-auth</url>
                </repository>
              </repositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>github-packages</activeProfile>
          </activeProfiles>
        </settings>
        EOF

    - name: Checkout phoebus repo
      uses: actions/checkout@v6
      with:
        repository: ControlSystemStudio/phoebus.git
        path: lib/phoebus
        ref: ${{ env.PHOEBUS_RELEASE}}

    - name: Patch AuthenticationScope - add KERBEROS
      shell: bash
      run: |
        sed -i 's/SAVE_AND_RESTORE("save-and-restore");/SAVE_AND_RESTORE("save-and-restore"),\n    KERBEROS("kerberos");/' \
          lib/phoebus/core/security/src/main/java/org/phoebus/security/tokens/AuthenticationScope.java

    - name: Build phoebus fnal product
      run: mvn clean install --batch-mode  -DskipTests=true -Ddocs=lib/phoebus/docs

    # The Phoebus application only requires the config and product-fnal/target folders.
    # The services JAR files are used in the deploy-containers job.
    # In the future, it may be worth separating the jobs for building the services and the Phoebus application.
    - uses: actions/upload-artifact@v7
      with:
        name: phoebus-fnal-${{ matrix.os }}
        path: |
          product-fnal/target/*.tar.gz
          config/
          lib/phoebus/services/alarm-logger/target/*.jar 
          alarm-server-fnal/target/fnal-alarm-server-*.jar
          lib/phoebus/services/alarm-server/target/lib/*.jar
          lib/phoebus/services/save-and-restore/target/service-save-and-restore-*.jar
          scan-server-fnal/target/fnal-scan-server*.jar
      if: github.event_name != 'pull_request'

  deploy-containers:
    runs-on: [ ubuntu-latest ]
    needs:  [ build ]
    if: github.event_name != 'pull_request'


    steps:

    - uses: actions/checkout@v6

    - name: Download phoebus build directory
      uses: actions/download-artifact@v8
      with:
        name: phoebus-fnal-ubuntu-latest
        path: .


    - name: Log in to Docker Registry
      uses: docker/login-action@v4
      with:
        registry: adregistry.fnal.gov
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Docker metadata for containers
      id: container-metadata
      uses: docker/metadata-action@v6
      with:
        images: |
          adregistry.fnal.gov/epics/alarm-logger
          adregistry.fnal.gov/epics/alarm-server
          adregistry.fnal.gov/epics/save-and-restore
          adregistry.fnal.gov/epics/scan-server
        tags: |
          type=raw,value=${{ env.IMAGE_VERSION }}

    - name: Build Alarm Logger container
      uses: docker/build-push-action@v7
      with:
        context: .
        file: containers/Dockerfile.alarmlogger
        push: true
        tags: adregistry.fnal.gov/epics/alarm-logger:${{ env.PHOEBUS_RELEASE }}_${{ github.run_number }}
        labels: ${{ steps.container-metadata.outputs.labels }}

    - name: Build Alarm Server container
      uses: docker/build-push-action@v7
      with:
        context: .
        file: containers/Dockerfile.alarmserver
        push: true
        tags: adregistry.fnal.gov/epics/alarm-server:${{ env.PHOEBUS_RELEASE }}_${{ github.run_number }}
        labels: ${{ steps.container-metadata.outputs.labels }}
  
    - name: Build Save and Restore container
      uses: docker/build-push-action@v7
      with:
        context: .
        file: containers/Dockerfile.saveandrestore
        push: true
        tags: adregistry.fnal.gov/epics/save-and-restore:${{ env.PHOEBUS_RELEASE }}_${{ github.run_number }}
        labels: ${{ steps.container-metadata.outputs.labels }}

    - name: Build scan server container
      uses: docker/build-push-action@v7
      with:
        context: .
        file: containers/Dockerfile.scanserver
        push: true
        tags: adregistry.fnal.gov/epics/scan-server:${{ env.PHOEBUS_RELEASE }}_${{ github.run_number }}
        labels: ${{ steps.container-metadata.outputs.labels }}
