name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: [ epics-build-test ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven


      # Since Phoebus is at gihthub.com domain we cant use checkout@v2 actions. 
      # See https://github.com/actions/checkout/discussions/511
      # We migth want to add phoebus as submodule
    - name: Checkout phoebus repo
      shell: bash
      run: git clone --depth 1 https://github.com/ControlSystemStudio/phoebus.git lib/phoebus

    - name: Build phoebus fnal product
      run: mvn clean install --batch-mode  --settings=config/settings.xml -DskipTests=true -Ddocs=lib/phoebus/docs
