name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: [ ubuntu-latest ]
    env:
      PHOEBUS_RELEASE: v4.7.3

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'


    - name: Checkout phoebus repo
      uses: actions/checkout@v4
      with:
        repository: ControlSystemStudio/phoebus.git
        path: lib/phoebus
        ref: ${{ env.PHOEBUS_RELEASE}}

    - name: Build phoebus fnal product
      run: mvn clean install --batch-mode  -DskipTests=true -Ddocs=lib/phoebus/docs

    - uses: actions/upload-artifact@v4
      with:
        name: phoebus-fnal
        path: .

  deploy-containers:
    runs-on: [ ubuntu-latest ]
    needs:  [ build ]
    if: github.event_name != 'pull_request'

    steps:
    - name: Download phoebus build directory
      uses: actions/download-artifact@v4
      with:
        name: phoebus-fnal
        path: .

    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: adregistry.fnal.gov
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Docker metadata for containers
      id: container-metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          adregistry.fnal.gov/epics/alarm-logger
          adregistry.fnal.gov/epics/alarm-server
          adregistry.fnal.gov/epics/save-and-restore
        tags: |
          type=edge
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ env.PHOEBUS_RELEASE }}_${{ github.run_number }}

    - name: Build Alarm Logger container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: containers/Dockerfile.alarmlogger
        push: true
        tags: adregistry.fnal.gov/epics/alarm-logger
        labels: ${{ steps.container-metadata.outputs.labels }}

    - name: Build Alarm Server container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: containers/Dockerfile.alarmserver
        push: true
        tags: adregistry.fnal.gov/epics/alarm-server
        labels: ${{ steps.container-metadata.outputs.labels }}

    - name: Build Save and Restore container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: containers/Dockerfile.saveandrestore
        push: true
        tags: adregistry.fnal.gov/epics/save-and-restore
        labels: ${{ steps.container-metadata.outputs.labels }}