name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven


    - name: Checkout phoebus repo
      uses: actions/checkout@v4
      repository: ControlSystemStudio/phoebus.git
      path: lib/phoebus

    - name: Build phoebus fnal product
      run: mvn clean install --batch-mode  --settings=config/settings.xml -DskipTests=true -Ddocs=lib/phoebus/docs
