name: Deploy pv-acsys package

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pv-acsys/**'

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Deploy pv-acsys jar
      run: mvn clean deploy
      working-directory: ./pv-acsys