name: Deploy pv-acsys package

on:
  push:
    branches: [ "main" ]
    paths:
      - 'pv-acsys/**'

permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Set up Maven settings for GitHub Packages
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF
  
    - name: Deploy pv-acsys jar
      run: mvn clean deploy
      working-directory: ./pv-acsys
